### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by ocupe** [Edinburgh-Genome-Foundry/sequenticon#2]
This is what I did:
1. `pip install sequenticon` into a fresh venv.
2. tried to run the example form the readme:
~~~ 
from sequenticon import sequenticon

# Write a sequence to a PNG sequenticon file
sequenticon("ATGGTGCA", size=120, output_path="icon.png")

# Get a self-contained "<img/>" HTML string, to embed in a webpage
img_tag = sequenticon("ATGGTGCA", size=60, output_format="html_image")
~~~

3. got this error
~~~
Traceback (most recent call last):
  File "/Users/Jonas/Documents/Programming/Temp_01/debug_it.py", line 1, in <module>
    from sequenticon import sequenticon
  File "/Users/Jonas/.virtualenvs/Temp_01/lib/python3.6/site-packages/sequenticon/__init__.py", line 5, in <module>
    from .sequenticon import (sequenticon,
  File "/Users/Jonas/.virtualenvs/Temp_01/lib/python3.6/site-packages/sequenticon/sequenticon.py", line 8, in <module>
    from pdf_reports import pug_to_html, write_report
  File "/Users/Jonas/.virtualenvs/Temp_01/lib/python3.6/site-packages/pdf_reports/__init__.py", line 1, in <module>
    from .pdf_reports import pug_to_html, write_report, GLOBALS
  File "/Users/Jonas/.virtualenvs/Temp_01/lib/python3.6/site-packages/pdf_reports/pdf_reports.py", line 2, in <module>
    import weasyprint
  File "/Users/Jonas/.virtualenvs/Temp_01/lib/python3.6/site-packages/weasyprint/__init__.py", line 375, in <module>
    from .css import preprocess_stylesheet  # noqa
  File "/Users/Jonas/.virtualenvs/Temp_01/lib/python3.6/site-packages/weasyprint/css/__init__.py", line 29, in <module>
    from . import computed_values
  File "/Users/Jonas/.virtualenvs/Temp_01/lib/python3.6/site-packages/weasyprint/css/computed_values.py", line 16, in <module>
    from .. import text
  File "/Users/Jonas/.virtualenvs/Temp_01/lib/python3.6/site-packages/weasyprint/text.py", line 18, in <module>
    import cairocffi as cairo
  File "/Users/Jonas/.virtualenvs/Temp_01/lib/python3.6/site-packages/cairocffi/__init__.py", line 41, in <module>
    cairo = dlopen(ffi, 'cairo', 'cairo-2')
  File "/Users/Jonas/.virtualenvs/Temp_01/lib/python3.6/site-packages/cairocffi/__init__.py", line 38, in dlopen
    raise OSError("dlopen() failed to load a library: %s" % ' / '.join(names))
OSError: dlopen() failed to load a library: cairo / cairo-2
~~~

**Comment by Zulko** [comment]
Thanks for raising this. It seems that Weasyprint is capricious on Windows. Since Weasyprint is not strictly needed in this library, I will make so that its import fails graciously on windows (and you will be able to use the other features).

If you want to be my test subject, please hold on a few minutes while I update my library. Then, If you really want to use weasyprint, the Windows instructions are here:

http://weasyprint.readthedocs.io/en/stable/install.html#windows

**Comment by Zulko** [comment]
I have now updated ``pdf_reports`` to fail silently if weasyprint bugs. This should allow you to generate sequenticons, but not as pdf reports.

Can you please try this update, then run your python snippet above again ?

```
pip install --upgrade git+git://github.com/Edinburgh-Genome-Foundry/pdf_reports.git
```

**Comment by ocupe** [comment]
@Zulko thank you for your help! Btw I'm on macOS but the problem was something else.
I was not aware that I had to install other dependencies. After I did `brew install python3 cairo pango gdk-pixbuf libffi` everything started to work. 
I checked out your readme and it does not mention the dependencies.
Maybe a hint would prevent this from happening again.

**Comment by Zulko** [comment]
Cool. I have also made weasyprint optional now. Closing this but ill make a mental note to add a link to the weasyprint install in the docs.
